### ISSUE TITLE
Soundex 

### ISSUE THREAD

**Issue by RLesur** [linogaliana/ensai-donnees-emergentes#25]
Pour illustrer le côté ancien des méthodes utilisées en analyse textuelle (https://github.com/linogaliana/ensai-donnees-emergentes/blob/master/textes.qmd#L15), j'aime bien l'exemple de Soundex cf.  https://en.wikipedia.org/wiki/Soundex

**Comment by linogaliana** [comment]
Merci je ne connaissais pas, ajouté avec 1bb666c10830afeffd2bae34a832b87b263ac116
