### ISSUE TITLE
Langages des scrapers 

### ISSUE THREAD

**Issue by RLesur** [linogaliana/ensai-donnees-emergentes#26]
Difficile d'avoir une métrique précise pour affirmer (https://github.com/linogaliana/ensai-donnees-emergentes/blob/master/textes.qmd#L94) mais j'aurais écrit "Python et JavaScript" car je pense que JavaScript est au moins aussi populaire si ce n'est plus que python pour les scrapers.

**Comment by linogaliana** [comment]
j'ai modéré le propos 0dd490f998441965511a522fd7d84ea38cff5345
